FROM python:3.6

ENV PIP_DISABLE_PIP_VERSION_CHECK 1 
ENV PYTHONDONTWRITEBYTECODE 1 
ENV PYTHONUNBUFFERED 1

WORKDIR /code/

COPY . /code/
COPY ./requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 8000