# Generated by Django 3.2.23 on 2023-12-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_backend', '0003_auto_20231227_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='orders_backend.user'),
        ),
    ]
