# Generated by Django 3.2.23 on 2023-12-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_backend', '0004_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
