# Generated by Django 3.2.23 on 2023-12-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_backend', '0006_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='store',
        ),
    ]
