# Generated by Django 3.2.23 on 2023-12-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_backend', '0008_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
