# Generated by Django 3.2.23 on 2024-01-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_backend', '0009_alter_product_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
