# Generated by Django 3.2.23 on 2024-01-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_backend', '0010_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('A', 'Accepted'), ('D', 'Declined'), ('P', 'Preparing'), ('C', 'Completed'), ('X', 'Cancelled')], default='R', max_length=1),
        ),
    ]
