# Generated by Django 3.2.23 on 2024-02-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_backend', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('A', 'Accepted'), ('D', 'Declined'), ('P', 'Paid'), ('O', 'On process'), ('C', 'Completed'), ('X', 'Cancelled')], default='R', max_length=1),
        ),
    ]
